package com.lawfirm.erp.modules.casemanagement.enums;

public enum TimelineEventType {
    MATTER_CREATED,
    COURT_CASE_ADDED,
    STAGE_CHANGE,
    MEDIATION_FAILED,
    MEDIATION_SUCCEEDED,
    COURT_EVENT_SCHEDULED,
    COURT_EVENT_HELD,
    COURT_EVENT_ADJOURNED,
    COURT_EVENT_CANCELLED,
    PARTY_ADDED,
    JUDGMENT_RECORDED,
    APPEAL_FILED,
    MATTER_NOTE_ADDED
}
