package com.lawfirm.erp.common.enums;

public enum PermissionAction {
    VIEW, CREATE, EDIT, DELETE,

    ACCESS,

    UPLOAD, DOWNLOAD, SHARE,

    EXPORT,

    SCHEDULE, UPDATE_STATUS, ASSIGN,

    APPROVE, REJECT, REVIEW,

    ARCHIVE, RESTORE, PRINT, FORWARD,

    CREDENTIAL_VIEW, CREDENTIAL_REVEAL
}